CREATE TABLE ARTICULOS(
    COD_ART NUMBER(6) CONSTRAINT ART_COD_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) CONSTRAINT ART_NOM_NN NOT NULL,
    PRECIO NUMBER(4,2) CONSTRAINT ART_PREC_CHK_NN CHECK (PRECIO >= 0) NOT NULL,
    STOCK NUMBER(4) CONSTRAINT ART_STO_CHK_NN CHECK (STOCK >= 0) NOT NULL,
    ID_PROV VARCHAR2(6) CONSTRAINT ART_ID_PROV_FK REFERENCES PROVEEDORES(ID_PROV)
);

CREATE TABLE MEDICAMENTOS(
    ID_MED NUMBER(6) CONSTRAINT MED_COD_MED_PK PRIMARY KEY,
    COD_ART NUMBER(6) CONSTRAINT MED_COD_FK REFERENCES ARTICULOS(COD_ART) NOT NULL,
    MASA NUMBER(4) CONSTRAINT MED_MAS_NN NOT NULL,
    UNIDAD VARCHAR2(2) CONSTRAINT MED_UNI_NN CHECK (LOWER(UNIDAD) IN ('g', 'mg', 'l', 'ml')) NOT NULL,
    RECETA VARCHAR2(2) CONSTRAINT MED_REC_CHK_NN CHECK (LOWER(RECETA) IN ('si', 'no')) NOT NULL
);

CREATE TABLE PROVEEDORES(
    ID_PROV VARCHAR2(6) CONSTRAINT PROV_ID_PROV_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50) CONSTRAINT PROV_NOM_PROV_NN NOT NULL,
    TELEFONO NUMBER(9) CONSTRAINT PROV_TEL_CHK_NN CHECK (TELEFONO = 9) NOT NULL,
    DIRECCION VARCHAR2(50) CONSTRAINT PROV_DIREC_NN NOT NULL
);