CREATE TABLE ARTICULOS (
    COGIDO NUMBER(6),
    NOMBRE VARCHAR2(100),
    PROVEEDOR VARCHAR2(50),
    PRECIO NUMBER(4,2),
    STOCK NUMBER(4),
    CONSTRAINT ART_COD_PK PRIMARY KEY (COGIDO),
    CONSTRAINT ART_NOM_NN NOT NULL (NOMBRE),
    CONSTRAINT ART_PROV_NN NOT NULL (PROVEEDOR),
    CONSTRAINT ART_PREC_CHK CHECK (PRECIO >= 0),
    CONSTRAINT ART_STO_CHK CHECK (STOCK >= 0)
);

CREATE TABLE MEDICAMENTOS (
    CODIGO NUMBER(6),
    MASA NUMBER(4),
    RECETA VARCHAR2(2),
    CONSTRAINT MED_COD_PK PRIMARY KEY (CODIGO),
    CONSTRAINT MED_MAS_NN NOT NULL,
    CONSTRAINT MED_REC_CHK CHECK (RECETA IN ('SI', 'NO'))
);

CREATE TABLE PROVEEDORES(
    ID_PROV VARCHAR2(6),
    NOM_PROV VARCHAR2(50),
    TELEFONO NUMBER(9),
    DIRECCION VARCHAR2(50),
    CONSTRAINT PROV_ID_PROV_PK PRIMARY KEY(ID_PROV),
    CONSTRAINT PROV_NOM_PROV_NN NOT NULL (NOM_PROV),
    CONSTRAINT PROV_TEL_CHK CHECK (TELEFONO = 9),
    CONSTRAINT PROV_DIREC_NN NOT NULL (DIRECCION)
);

