CREATE TABLE SUPPLIERS(
    ID_SUP INTEGER PRIMARY KEY AUTOINCREMENT,
    SUP_NAME VARCHAR2(50) CONSTRAINT SUP_NAME_SUP_NN NOT NULL,
    PHONE VARCHAR2(13) CONSTRAINT SUP_PHONE_CHK_NN CHECK (LENGTH(PHONE) = 9) NOT NULL,
    ADDRESS VARCHAR2(150) CONSTRAINT SUP_ADDRESS_NN NOT NULL
);

CREATE TABLE ITEMS(
    ID_ITEM INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEM_NAME VARCHAR2(100) CONSTRAINT ITEM_NAME_NN NOT NULL,
    PRICE NUMBER(4,2) CONSTRAINT ITEM_PRICE_CHK_NN CHECK (PRICE >= 0) NOT NULL,
    STOCK NUMBER(4) CONSTRAINT ITEM_STOCK_CHK_NN CHECK (STOCK >= 0) NOT NULL,
    SUP_ID INTEGER CONSTRAINT ITEM_ID_SUP_FK REFERENCES SUPPLIERS(ID_SUP)
);

CREATE TABLE MEDICINE(
    ID_MED INTEGER(6) PRIMARY KEY,
    ITEM_ID INTEGER CONSTRAINT MED_ID_FK REFERENCES ITEMS(ID_ITEM),
    MASS NUMBER(4) CONSTRAINT MED_MASS_NN NOT NULL,
    UNIT VARCHAR2(2) CONSTRAINT MED_UNI_NN CHECK (LOWER(UNIT) IN ('g', 'mg', 'l', 'ml')) NOT NULL,
    PRESCRIPTION VARCHAR2(2) CONSTRAINT MED_PRES_CHK_NN CHECK (LOWER(PRESCRIPTION) IN ('si', 'no')) NOT NULL
);

CREATE TABLE USERS(
    ID_USR INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR2(50) CONSTRAINT USR_NAME_NN NOT NULL,
    PASSWORD VARCHAR2(50) CONSTRAINT USR_PASS_NN NOT NULL,
    PERMISSION VARCHAR2(2) CONSTRAINT USR_PER_CHK_NN CHECK (LOWER(PERMISSION) IN ('ad', 'us')) NOT NULL
);

-- INSERTING DATA FROM SUPPLIERS

BEGIN
-- INSERT INTO SUPPLIERS VALUES (1, 'ALLIANCE HEALTHCARE ESPAÑA, S.A.', '900533721', 'Avda de la Industria, 29 - Polígono Industrial La Cantueña');
-- INSERT INTO SUPPLIERS VALUES (2, 'EUROLAB FARMA S.A.L.', '916775025', 'Av. Sistema Solar 26, CP. 28830 Madrid.');
INSERT INTO SUPPLIERS VALUES (1, 'TEVA S.A.', '915359180', 'Calle Anabel Segura, nº 11 Edificio Albatros B, 1ª planta 28108 - Alcobendas - Madrid');
INSERT INTO SUPPLIERS VALUES (2, 'LABORATORIOS COMBIX S.L.U', '914904253', 'Calle Badajoz 2, 28223 Pozuelo de Alarcón, Madrid');
END;


-- INSERTING DATA FROM ITEMS

BEGIN
INSERT INTO ITEMS (ITEM_NAME, PRICE, STOCK, SUP_ID) VALUES ('IBUPROFENO TEVA 600 MG', 1.97, 0, 1);
INSERT INTO ITEMS (ITEM_NAME, PRICE, STOCK, SUP_ID) VALUES ('PARACETAMOL PHARMA COMBIX 1G COMPRIMIDOS EFG', 2.50, 0, 2);

INSERT INTO ITEMS (ITEM_NAME, PRICE, STOCK, SUP_ID) VALUES ('ÁCIDO ALENDRÓNICO SEMANAL PHARMA COMBIX EFG', 9.99, 0, 2);
END;

--INSERTING DATA FROM MEDICINE

BEGIN
INSERT INTO MEDICINE VALUES (625209, 1, 600, 'mg', 'no');
INSERT INTO MEDICINE VALUES (663664, 2, 1, 'g', 'no');
INSERT INTO MEDICINE VALUES (659132, 3, 70, 'mg', 'si');


END;

--INSERTING DATA FROM USERS

BEGIN
INSERT INTO USERS VALUES (1, 'admin', 'admin', 'ad');
INSERT INTO USERS VALUES (2, 'user', 'user', 'us');
END;
