CREATE TABLE SUPPLIERS(
    ID_SUP INTEGER PRIMARY KEY AUTOINCREMENT,
    SUP_NAME VARCHAR2(50) CONSTRAINT SUP_NAME_SUP_NN NOT NULL,
    PHONE VARCHAR2(13) CONSTRAINT SUP_PHONE_CHK_NN CHECK (LENGTH(PHONE) = 9) NOT NULL,
    ADDRESS VARCHAR2(50) CONSTRAINT SUP_ADDRESS_NN NOT NULL
);

CREATE TABLE ITEMS(
    ID_ITEM INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEM_NAME VARCHAR2(100) CONSTRAINT ITEM_NAME_NN NOT NULL,
    PRICE NUMBER(4,2) CONSTRAINT ITEM_PRICE_CHK_NN CHECK (PRICE >= 0) NOT NULL,
    STOCK NUMBER(4) CONSTRAINT ITEM_STOCK_CHK_NN CHECK (STOCK >= 0) NOT NULL,
    SUP_ID INTEGER CONSTRAINT ITEM_ID_SUP_FK REFERENCES SUPPLIERS(ID_SUP)
);

CREATE TABLE MEDICINE(
    ID_MED INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEM_ID INTEGER CONSTRAINT MED_ID_FK REFERENCES ITEMS(ID_ITEM),
    MASS NUMBER(4) CONSTRAINT MED_MASS_NN NOT NULL,
    UNIT VARCHAR2(2) CONSTRAINT MED_UNI_NN CHECK (LOWER(UNIT) IN ('g', 'mg', 'l', 'ml')) NOT NULL,
    PRESCRIPTION VARCHAR2(2) CONSTRAINT MED_PRES_CHK_NN CHECK (LOWER(PRESCRIPTION) IN ('si', 'no')) NOT NULL
);

CREATE TABLE USERS(
    ID_USR INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR2(50) CONSTRAINT USR_NAME_NN NOT NULL,
    PASSWORD VARCHAR2(50) CONSTRAINT USR_PASS_NN NOT NULL,
    PERMISSION VARCHAR2(2) CONSTRAINT USR_PER_CHK_NN CHECK (LOWER(PERMISSION) IN ('ad', 'us')) NOT NULL
);