CREATE TABLE PROVEEDORES(
    ID_PROV INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE VARCHAR2(50) CONSTRAINT PROV_NOM_PROV_NN NOT NULL,
    TELEFONO VARCHAR2(13) CONSTRAINT PROV_TEL_CHK_NN CHECK (LENGTH(TELEFONO) = 9) NOT NULL,
    DIRECCION VARCHAR2(50) CONSTRAINT PROV_DIREC_NN NOT NULL
);

CREATE TABLE ARTICULOS(
    COD_ART INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE VARCHAR2(100) CONSTRAINT ART_NOM_NN NOT NULL,
    PRECIO NUMBER(4,2) CONSTRAINT ART_PREC_CHK_NN CHECK (PRECIO >= 0) NOT NULL,
    STOCK NUMBER(4) CONSTRAINT ART_STO_CHK_NN CHECK (STOCK >= 0) NOT NULL,
    ID_PROV INTEGER CONSTRAINT ART_ID_PROV_FK REFERENCES PROVEEDORES(ID_PROV)
);

CREATE TABLE MEDICAMENTOS(
    ID_MED INTEGER PRIMARY KEY AUTOINCREMENT,
    COD_ART INTEGER CONSTRAINT MED_COD_FK REFERENCES ARTICULOS(COD_ART),
    MASA NUMBER(4) CONSTRAINT MED_MAS_NN NOT NULL,
    UNIDAD VARCHAR2(2) CONSTRAINT MED_UNI_NN CHECK (LOWER(UNIDAD) IN ('g', 'mg', 'l', 'ml')) NOT NULL,
    RECETA VARCHAR2(2) CONSTRAINT MED_REC_CHK_NN CHECK (LOWER(RECETA) IN ('si', 'no')) NOT NULL
);

CREATE TABLE USUARIOS(
    ID_USU INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE VARCHAR2(50) CONSTRAINT USU_NOM_USU_NN NOT NULL,
    PASSWORD VARCHAR2(50) CONSTRAINT USU_PASS_USU_NN NOT NULL,
    PERMISO VARCHAR2(2) CONSTRAINT USU_PER_CHK_NN CHECK (LOWER(PERMISO) IN ('ad', 'us')) NOT NULL
);
