CREATE TABLE ARTICULOS(
    CODIGO NUMBER(6) CONSTRAINT ART_COD_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100) CONSTRAINT ART_NOM_NN NOT NULL,
    PRECIO NUMBER(4,2) CONSTRAINT ART_PREC_CHK_NN CHECK (PRECIO >= 0) NOT NULL,
    STOCK NUMBER(4) CONSTRAINT ART_STO_CHK_NN CHECK (STOCK >= 0) NOT NULL,
    ID_PROV VARCHAR2(6) CONSTRAINT ART_ID_PROV_FK REFERENCES PROVEEDORES
);

CREATE TABLE MEDICAMENTOS (
    CODIGO_MED NUMBER(6) CONSTRAINT MED_COD_MED_PK PRIMARY KEY,
    CODIGO NUMBER(6) CONSTRAINT MED_COD_FK REFERENCES ARTICULOS,
    MASA NUMBER(4) CONSTRAINT MED_MAS_NN NOT NULL,
    RECETA VARCHAR2(2) CONSTRAINT MED_REC_CHK_NN CHECK (RECETA IN ('SI', 'NO')) NOT NULL
);

CREATE TABLE PROVEEDORES(
    ID_PROV VARCHAR2(6) CONSTRAINT PROV_ID_PROV_PK PRIMARY KEY,
    NOM_PROV VARCHAR2(50) CONSTRAINT PROV_NOM_PROV_NN NOT NULL,
    TELEFONO NUMBER(9) CONSTRAINT PROV_TEL_CHK_NN CHECK (TELEFONO = 9) NOT NULL,
    DIRECCION VARCHAR2(50) CONSTRAINT PROV_DIREC_NN NOT NULL
);